apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiboweb-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: fiboweb
          image: vikalf/fiboform.web
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: API_URL
              value: fiboapi-cluster-ip-service