apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiboapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: fiboapi
          image: vikalf/fiboform.api:v2.1
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_INSTANCE
              value: master
            - name: PG_SERVER
              value: postgres-cluster-ip-service
            - name: PG_PORT
              value: '5432'
            - name: PG_DATABASE
              value: maindb
            - name: PG_USER
              value: superuser
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-password
                  key: PG_PASSWORD