apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiboweb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: fiboweb
          image: vikalf/fiboform.web:v2.1
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: API_BASE_URL
              value: http://fiboapi-cluster-ip-service
            - name: FIBO_PAYLOAD_URL
              value: /fibo
            - name: FIBO_SEARCH_URL
              value: /fibo/{0}