version: '3'
services:
  redis-server:
    image: 'redis'
    ports:
      - "6379:6379"
  postgres-server:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=password01
      - POSTGRES_USER=superuser
      - POSTGRES_DB=maindb
    ports:
      - "5432:5432"
#  fiboform-api:
#    restart: always
#    build: 
#      dockerfile: Dockerfile.FiboFormApi
#      context: .
#    ports:
#      - "81:80"
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - GRPC_Proxy=192.168.99.100:50051
#      - REDIS_HOST=192.168.99.100:6379
#      - PG_SERVER=192.168.99.100
#      - PG_PORT=5432
#      - PG_DATABASE=maindb
#      - PG_USER=superuser
#      - PG_PASSWORD=password01
#  fiboform-web:
#    restart: always
#    build:
#      dockerfile: Dockerfile.FiboFormWeb
#      context: .
#    ports:
#      - "80:80"
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - API_URL=http://192.168.99.100:81


#  fibo-service:
#    restart: always
#    build:
#      dockerfile: Dockerfile.FiboService
#      context: .
#    ports:
#      - "50051:50051"
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - REDIS_HOST=192.168.99.100:6379
#      - PG_SERVER=192.168.99.100
#      - PG_PORT=5432
#      - PG_DATABASE=maindb
#      - PG_USER=superuser
#      - PG_PASSWORD=password01