FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY . .
WORKDIR "/src/Fibo.Service"

FROM build AS publish
RUN dotnet publish "Fibo.Service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
EXPOSE 50051
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Fibo.Service.dll"]